version: '3.8'

services:
    front:
        container_name: front
        build:
            context: ./front/
            dockerfile: ./compose/local/Dockerfile
        image: front
        depends_on:
            - back
        volumes:
            - ./front/:/app
        ports:
            - "3000:3000"
        command: /start

    back:
        container_name: back
        build:
            context: ./back/
            dockerfile: ./compose/local/Dockerfile
        image: back
        volumes:
            - ./back/:/server
        env_file:
            - back/.env/back.env
        ports:
            - "4000:4000"
        command: /start

