#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

printf "\n\n"
printf "####################################\n"
printf "#     Instalando dependências      #\n"
printf "####################################\n"
printf "\n"
npm install

printf "\n"
printf "#############################\n"
printf "#   Inicializando o Front   #\n"
printf "#############################\n"

printf "\n\n"
printf "#########################################\n"
printf "# Compilando e servindo a aplicação...  #\n"
printf "#########################################\n"
printf "\n\n"

npm run dev

